DATA:
  DATASET: 'CISOL_TD-TSR'
  ROOT: '/kaggle/input/construction-industry-steel-ordering-lists-cisol/cisol_TD-TSR'

MODEL:
  NUM_CLASSES: 6

MISC:
  RUN_NAME: 'CISOL_TD-TSR_SecondRun'
  RESULTS_CSV: '/kaggle/working/repository_content/results'
  SAVE_MODEL_PATH: '/kaggle/working/repository_content/saved_models'
  PRETRAINED_WEIGHTS: '/kaggle/input/pretrained_coco_default/pytorch/coco_default_table_detection/1/CISOL_TD-TSR_firstRun.pth'

TRAIN:
  BASE_LR: 0.0001
  MILESTONES: [10, 20]
  GAMMA: 0.1
  BATCH_SIZE: 4
  NUM_EPOCHS: 30
  EARLY_STOPPING: True

AUGMENTATION:
  HORIZONTAL_FLIP_PROB: 0.5
  ROTATION_DEGREES: 11
